# Generated by Django 6.1.1 on 2026-09-26 03:20

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Comercial')),
                ('legal_name', models.CharField(blank=True, max_length=250, verbose_name='Razón Social / Propietario')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='RTN / Identificación Fiscal')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono / WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo de la Empresa')),
                ('receipt_prefix', models.CharField(blank=True, default='', max_length=20, verbose_name='Prefijo de Recibo (opcional, ej: REC- o vacío)')),
                ('receipt_start_number', models.PositiveIntegerField(default=1, verbose_name='Número inicial de recibos (ej: 1 para 0001)')),
                ('receipt_padding', models.PositiveSmallIntegerField(default=4, verbose_name='Dígitos de relleno con ceros (ej: 4 genera 0001)')),
                ('receipt_footer_note', models.TextField(blank=True, default='Gracias por su pago puntual. Este documento es un comprobante válido.', verbose_name='Nota al pie de los recibos')),
                ('default_exchange_rate', models.DecimalField(decimal_places=4, default=Decimal('24.7500'), max_digits=10, verbose_name='Tasa de cambio predeterminada (USD -> HNL)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('rate_usd_to_hnl', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Tasa USD a HNL')),
                ('source', models.CharField(default='API', max_length=50, verbose_name='Fuente (API / Manual)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de Tasa de Cambio',
                'verbose_name_plural': 'Registros de Tasa de Cambio',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
