# Generated by Django 6.1.1 on 2026-10-02 00:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='initial_balance_hnl',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fondo inicial disponible con el que arrancó la empresa antes de registrar movimientos', max_digits=12, verbose_name='Saldo Inicial de Caja en Lempiras (L HNL)'),
        ),
        migrations.AddField(
            model_name='company',
            name='initial_balance_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Saldo Inicial de Caja en Dólares ($ USD)'),
        ),
    ]
