# Generated by Django 6.1.1 on 2026-10-02 01:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_initial_balance_hnl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='exchange_rate_api_key',
            field=models.CharField(blank=True, default='', help_text='Clave de API si tu proveedor (ej. ExchangeRate-API, Fixer) la solicita', max_length=200, verbose_name='API Key del Servicio (Opcional)'),
        ),
        migrations.AddField(
            model_name='company',
            name='exchange_rate_api_url',
            field=models.CharField(blank=True, default='https://open.er-api.com/v6/latest/USD', help_text='Endpoint para consultar tasa USD a HNL. Ej: https://open.er-api.com/v6/latest/USD o https://v6.exchangerate-api.com/v6/{api_key}/latest/USD', max_length=500, verbose_name='URL del Endpoint de la API'),
        ),
        migrations.AddField(
            model_name='company',
            name='exchange_rate_auto_update',
            field=models.BooleanField(default=True, help_text='Si está activo, consultará la API al inicio del día. Siempre puedes modificar manualmente la tasa en cada recibo o gasto.', verbose_name='Consultar API automáticamente en tiempo real'),
        ),
        migrations.AddField(
            model_name='exchangeratelog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rate_logs', to='core.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='default_exchange_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('24.7500'), help_text='Tasa de respaldo utilizada si no hay conexión a la API o si se desactiva la consulta automática', max_digits=10, verbose_name='Tasa de cambio predeterminada / fija (USD -> HNL)'),
        ),
    ]
