# Generated by Django 6.1.1 on 2026-10-02 01:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_exchange_rate_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='current_exchange_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('24.7500'), help_text='Tasa guardada automáticamente una vez al día por la tarea programada. Es la que se muestra en el sistema y en la página pública.', max_digits=10, verbose_name='Tasa de cambio actual almacenada (USD -> HNL)'),
        ),
        migrations.AddField(
            model_name='company',
            name='exchange_rate_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de última actualización de la tasa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='exchange_rate_auto_update',
            field=models.BooleanField(default=True, help_text='Si está activo, la tarea programada (entre 1:00 AM y 4:00 AM) consultará la API y guardará la tasa del día.', verbose_name='Actualizar API automáticamente 1 vez al día'),
        ),
    ]
