# Generated by Django 6.1.1 on 2026-09-26 03:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField(verbose_name='Secuencia Numérica')),
                ('receipt_number', models.CharField(max_length=50, verbose_name='Número de Recibo (ej: 0001)')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión')),
                ('billing_month', models.PositiveSmallIntegerField(verbose_name='Mes de Cobro (1-12)')),
                ('billing_year', models.PositiveSmallIntegerField(verbose_name='Año de Cobro')),
                ('concept', models.CharField(max_length=300, verbose_name='Concepto / Detalle del Pago')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto en Dólares ($ USD)')),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Tasa de Cambio (USD a HNL)')),
                ('amount_hnl', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto en Lempiras (L HNL)')),
                ('payment_method', models.CharField(choices=[('transfer', 'Transferencia Bancaria'), ('cash', 'Efectivo'), ('deposit', 'Depósito Bancario'), ('card', 'Tarjeta de Crédito / Débito'), ('other', 'Otro Medio')], default='transfer', max_length=30, verbose_name='Forma de Pago')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia / N° de Transacción')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('status', models.CharField(choices=[('paid', 'Emitido / Pagado'), ('cancelled', 'Anulado')], default='paid', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='clients.client', verbose_name='Cliente')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='core.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Emitido por')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'ordering': ['-issue_date', '-sequence_number'],
                'unique_together': {('company', 'sequence_number')},
            },
        ),
    ]
