# Generated by Django 6.1.1 on 2026-09-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='receipt_proofs/', verbose_name='Archivo de Comprobante de Pago'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment_proof_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Registro del Comprobante'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='amount_hnl',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total en Lempiras (L HNL)'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Base en Dólares ($ USD)'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('transfer', 'Transferencia Bancaria'), ('cash', 'Efectivo'), ('deposit', 'Depósito Bancario'), ('card', 'Tarjeta de Crédito / Débito'), ('other', 'Otro Medio')], default='transfer', max_length=30, verbose_name='Forma de Pago'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referencia / N° de Comprobante'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('paid', 'Emitido / Activo'), ('cancelled', 'Anulado')], default='paid', max_length=20, verbose_name='Estado'),
        ),
    ]
