# Generated by Django 6.1.1 on 2026-09-26 06:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_first_payment_usd_client_payment_parts_and_more'),
        ('core', '0001_initial'),
        ('receipts', '0002_receipt_payment_proof_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='external_client_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Empresa / Cliente Externo (No registrado)'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='is_extra_charge',
            field=models.BooleanField(default=False, verbose_name='Es Monto Extra (Fuera del cobro mensual)'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='amount_hnl',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto en Lempiras (L HNL)'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto en Dólares ($ USD)'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='clients.client', verbose_name='Cliente Registrado'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='receipt_proofs/', verbose_name='Comprobante de Pago (Imagen o PDF)'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_proof_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Subida del Comprobante'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referencia / N° de Transacción'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('paid', 'Emitido / Pagado'), ('cancelled', 'Anulado')], default='paid', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='ExtraIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('external', 'Empresa / Cliente Externo (No registrado - Solo registro de ingreso)'), ('registered', 'Empresa / Cliente Registrado (Monto extra fuera del cobro mensual)')], default='external', max_length=20, verbose_name='Tipo de Origen del Ingreso')),
                ('external_company_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre de Empresa o Cliente Externo (No registrado)')),
                ('income_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Ingreso')),
                ('concept', models.CharField(max_length=300, verbose_name='Concepto / Descripción del Ingreso')),
                ('currency', models.CharField(choices=[('USD', 'Dólares ($ USD)'), ('HNL', 'Lempiras (L HNL)')], default='USD', max_length=10, verbose_name='Moneda del Monto')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Ingresado')),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Tasa de Cambio (USD a HNL)')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto en Dólares ($ USD)')),
                ('amount_hnl', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto en Lempiras (L HNL)')),
                ('payment_reference', models.CharField(blank=True, default='', max_length=100, verbose_name='Referencia / N° de Transacción (Opcional)')),
                ('payment_proof', models.FileField(blank=True, null=True, upload_to='extra_income_proofs/', verbose_name='Comprobante de Pago (Imagen o PDF)')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones (Opcional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_incomes', to='clients.client', verbose_name='Empresa / Cliente Registrado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_incomes', to='core.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_extra_incomes', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Ingreso Extra / Externo',
                'verbose_name_plural': 'Ingresos Extra / Externos',
                'ordering': ['-income_date', '-created_at'],
            },
        ),
    ]
