# Generated by Django 6.1.1 on 2026-09-26 03:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Completo / Razón Social')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='RTN / DNI / Identificación')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono / WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('monthly_fee_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cobro Mensual ($ USD)')),
                ('billing_day', models.PositiveSmallIntegerField(default=1, verbose_name='Día de cobro del mes (1 - 31)')),
                ('default_concept', models.CharField(default='Cuota mensual de servicio', max_length=250, verbose_name='Concepto de cobro predeterminado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas u Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
    ]
