# Generated by Django 6.1.1 on 2026-09-26 04:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='first_payment_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto 1er Pago ($ USD)'),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_parts',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 solo pago al mes (Monto completo)'), (2, 'En 2 partes al mes (Dos fechas de cobro)')], default=1, verbose_name='Modalidad de Pago'),
        ),
        migrations.AddField(
            model_name='client',
            name='second_billing_day',
            field=models.PositiveSmallIntegerField(blank=True, default=30, null=True, verbose_name='Día del 2do Cobro (1 - 31)'),
        ),
        migrations.AddField(
            model_name='client',
            name='second_payment_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto 2do Pago ($ USD)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='billing_day',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Día del 1er Cobro (1 - 31)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='monthly_fee_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cobro Mensual Total ($ USD)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre Completo / Cliente'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tax_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='DNI / RTN (Opcional)'),
        ),
    ]
