# Generated by Django 6.1.1 on 2026-09-26 03:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('company', 'Gasto de Empresa'), ('personal', 'Gasto Personal')], default='company', max_length=20, verbose_name='Tipo de Gasto')),
                ('category', models.CharField(choices=[('services', 'Servicios Públicos (Luz, Agua, Internet, Celular)'), ('rent', 'Alquiler y Oficina'), ('payroll', 'Sueldos / Salarios / Honorarios'), ('supplies', 'Materiales, Insumos y Equipos'), ('transport', 'Transporte / Combustible / Mantenimiento Vehicular'), ('food', 'Alimentación y Viáticos'), ('taxes', 'Impuestos, Tasas y Permisos'), ('personal_draw', 'Retiro / Gastos del Propietario'), ('marketing', 'Publicidad y Marketing'), ('maintenance', 'Mantenimiento y Reparaciones'), ('other', 'Otros Gastos Varios')], default='other', max_length=50, verbose_name='Categoría')),
                ('title', models.CharField(max_length=200, verbose_name='Concepto / Título del Gasto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción / Detalle')),
                ('expense_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Gasto')),
                ('currency', models.CharField(choices=[('HNL', 'Lempiras (L HNL)'), ('USD', 'Dólares ($ USD)')], default='HNL', max_length=5, verbose_name='Moneda de Origen')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Registrado')),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Tasa de Cambio (USD -> HNL)')),
                ('amount_hnl', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Equivalente en Lempiras (L)')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Equivalente en Dólares ($)')),
                ('beneficiary', models.CharField(blank=True, max_length=200, verbose_name='Beneficiario / Proveedor / Comercio')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia Bancaria'), ('card', 'Tarjeta de Débito / Crédito'), ('check', 'Cheque'), ('other', 'Otro')], default='cash', max_length=30, verbose_name='Método de Pago')),
                ('receipt_voucher', models.FileField(blank=True, null=True, upload_to='expense_vouchers/', verbose_name='Comprobante / Foto / Factura')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Bitácora de Gastos',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
