# Generated by Django 6.1.1 on 2026-10-02 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_initial_balance_hnl_and_more'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ej: Energía Eléctrica (Luz), Internet de Oficina, Renta de Local', max_length=200, verbose_name='Concepto / Servicio')),
                ('category', models.CharField(choices=[('services', 'Servicios Públicos (Luz, Agua, Internet, Celular)'), ('rent', 'Alquiler y Oficina'), ('payroll', 'Sueldos / Salarios / Honorarios'), ('supplies', 'Materiales, Insumos y Equipos'), ('transport', 'Transporte / Combustible / Mantenimiento Vehicular'), ('food', 'Alimentación y Viáticos'), ('taxes', 'Impuestos, Tasas y Permisos'), ('personal_draw', 'Retiro / Gastos del Propietario'), ('marketing', 'Publicidad y Marketing'), ('maintenance', 'Mantenimiento y Reparaciones'), ('other', 'Otros Gastos Varios')], default='services', max_length=50, verbose_name='Categoría')),
                ('expense_type', models.CharField(choices=[('company', 'Gasto de Empresa'), ('personal', 'Gasto Personal')], default='company', max_length=20, verbose_name='Tipo de Gasto')),
                ('due_day', models.PositiveSmallIntegerField(default=1, verbose_name='Día de Pago en el Mes (1 - 31)')),
                ('currency', models.CharField(choices=[('HNL', 'Lempiras (L HNL)'), ('USD', 'Dólares ($ USD)')], default='HNL', max_length=5, verbose_name='Moneda')),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Presupuestado / Estimado')),
                ('beneficiary', models.CharField(blank=True, help_text='Ej: ENEE, Claro, Arrendador', max_length=200, verbose_name='Beneficiario / Proveedor')),
                ('service_code', models.CharField(blank=True, help_text='Ej: Clave de cliente, N° de contador o contrato', max_length=100, verbose_name='N° de Cuenta / Clave / Contador (Opcional)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas u Observaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_payments', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Pago Recurrente / Presupuesto',
                'verbose_name_plural': 'Pagos Recurrentes & Servicios',
                'ordering': ['due_day', 'title'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='recurring_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to='expenses.recurringpayment', verbose_name='Pago Recurrente Asociado'),
        ),
    ]
